routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function(){ 
    return redirect()->route('login');
})
->name('landing');
Route::get('/chatbox',function(){
    return view('front.chatBox');
})->name('chatbox');
// Route::post('/botman', [App\Http\Controllers\BotManController::class,'handle']);
Route::match(['get', 'post'], '/botman', [App\Http\Controllers\BotManController::class,'handle'])->name('botman');

Route::get('login/locked', [App\Http\Controllers\Auth\LoginController::class,'locked'])->middleware('auth')->name('login.locked');
Route::post('login/locked', [App\Http\Controllers\Auth\LoginController::class,'unlock'])->name('login.unlock');

// Route::get('/', [App\Http\Controllers\FrontController::class,'index'])->name('landing');
Route::get('about', [App\Http\Controllers\FrontController::class,'about'])->name('about');
Route::get('team', [App\Http\Controllers\FrontController::class,'team'])->name('team');
Route::get('/service', [App\Http\Controllers\FrontController::class,'service'])->name('service');
Route::get('/chatbot', [App\Http\Controllers\FrontController::class,'chatbot'])->name('chatbot');
Route::get('/voice_chatbot', [App\Http\Controllers\FrontController::class,'voiceChatbot'])->name('voiceChatbot');
Route::get('/contact', [App\Http\Controllers\FrontController::class,'contact'])->name('contact');
Route::get('/faq', [App\Http\Controllers\FrontController::class,'faq'])->name('faq');
Route::get('/blog', [App\Http\Controllers\FrontController::class,'blog'])->name('blog');
Route::get('/blog_detail', [App\Http\Controllers\FrontController::class,'blogDetail'])->name('blogDetail');
Route::get('/privacy', [App\Http\Controllers\FrontController::class,'privacy'])->name('privacy');
Route::get('/terms', [App\Http\Controllers\FrontController::class,'terms'])->name('terms');
Route::post('/contact', [App\Http\Controllers\FrontController::class,'contactStore'])->name('contact-post');
Route::get('/read-aloud', [App\Http\Controllers\FrontController::class,'readAloud'])->name('read-aloud');



Route::group(['prefix'=>'/','middleware'=>['auth'],'namespace'=>'App\Http\Controllers'],function(){
/* Route::get('/dashboard', function () {
    return view('dashboard.dashboard');
})->name('dashboard'); */

Route::patch('/change-pwd','HomeController@changePassword')->name('change-password');
Route::patch('/delete-account','HomeController@deleteAccount')->name('delete-account');
Route::patch('/update-me','HomeController@updateMe')->name('update-me');
Route::patch('/screen-lock','HomeController@screenLock')->name('screenLock');// screen-lock

Route::group(['prefix'=>'mail'],function(){
Route::resource('inbox','InboxController')->only(['index','show']);
Route::resource('sent','OutboxController')->only(['index','show']);
Route::resource('draft','DraftController')->only(['index','show']);
Route::resource('trash','TrashController')->only(['index','show']);
Route::resource('imp','ImportantController')->only(['index','show']);
Route::resource('/','MailController',
	['names' => array(
		// 'show' => 'mail.show',
		'edit' => 'mail.edit',
		'store' => 'mail.store')])
->except(['update','destroy','index','create','show']);
Route::get('/compose','MailController@compose')->name('mail.compose');
Route::delete('inbox/delete/{id?}','InboxController@deleteRecord')->name('inbox.delete');
Route::delete('sent/delete/{id?}','OutboxController@deleteRecord')->name('sent.delete');
Route::delete('trash/delete{id?}','TrashController@deleteRecord')->name('trash.delete');
Route::delete('draft/delete/{id?}','DraftController@deleteRecord')->name('draft.delete');
Route::delete('imp/delete/{id?}','ImportantController@deleteRecord')->name('imp.delete');
Route::get('trash/{id}/make-imp','TrashController@makeItImp')->name('trash.imp');
Route::get('draft/{id}/make-imp','DraftController@makeItImp')->name('draft.imp');
Route::get('inbox/{id}/make-imp','InboxController@makeItImp')->name('inbox.imp');
Route::get('sent/{id}/make-imp','OutboxController@makeItImp')->name('sent.imp');
Route::get('mail/{dir}/{file_name}/dowload-attachment','MailController@attachDownload')->name('download-attach');
Route::get('mail/{dir}/{file_name}/display-attachment','MailController@attachDisplay')->name('display-attach');
Route::get('{mail_id}/{mail_type}/reply','MailController@reply')->name('mail.reply');
Route::get('mail-user/search', 'MailController@mailUserSearch')->name('navbar-search');
Route::get('/search', 'MailController@mailSearch')->name('mail-search');
Route::get('{user_id}/compose','MailController@mailSendBySearch')->name('mail-Send-by-search');
Route::get('/created_at', 'MailController@createDiffForHumans')->name('created_at');
Route::get('/attachment', 'MailController@attachmentsByMailId')->name('isExistsAttachment');
Route::get('subject/create', 'MailController@subjectCreate')->name('subjectCreate');
});
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//for admin
Route::group(['prefix' => 'admin','middleware' => ['auth','admin'],'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/dashboard', 'Homecontroller@admin')->name('admin');
    Route::resource('user', 'UserController');// for user manager
    Route::get('/user/{id}/change-password','UserController@showPasswordChangeForm')->name('change-pwd');
    Route::patch('/user/{id}/change-password','UserController@updatePassword')->name('user-update-password');
    Route::get('/user/status-change/{id}/{status}','UserController@changeStatus')->name('user-change-status');
});

//for normal user
Route::group(['prefix' => '/','middleware' => ['auth','user'],'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'user'])->middleware('auth.lock')->name('user');
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'user'])->middleware('auth.lock')->name('dashboard');
});

// for chatbot

// Route::match(['get', 'post'], '/chatbot/botman', [App\Http\Controllers\BotManController::class, 'handle']);
/* Route::post('/chatbot/botman',function(){
    app('botman')->listen();
}); */

resources/views/dashboard/dashboard.blade.php
@extends('layouts.dashboard')
@section('title','Dashboard')
@section('content-header')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Dashboard</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">VBES</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
@endsection
@section('content')
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>
                            @php
                                $mails = DB::table('inboxes')
                                 ->where('user_id',auth()->user()->id)
                                 ->count();
                                 echo $mails;
                            @endphp
                        </h3>
                        <p>Inbox</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="{{ route('inbox.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                    <h3>
                        @php
                        $mails = DB::table('outboxes')
                            ->where('user_id',auth()->user()->id)
                            ->count();
                        echo $mails;
                        @endphp
                    </h3>

                        <p>Sent</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{{ route('sent.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                    <h3>
                        @php
                        $mails = DB::table('drafts')
                            ->where('user_id',auth()->user()->id)
                            ->count();
                        echo $mails;
                        @endphp
                    </h3>

                        <p>Draft</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="{{route('draft.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                    <h3>
                        @php
                        $mails = DB::table('trashes')
                            ->where('user_id',auth()->user()->id)
                            ->count();
                        echo $mails;
                        @endphp
                    </h3>

                        <p>Trash</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="{{route('trash.index')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
        <!-- /.row -->
        </div>
@endsection

resources/views/dashboard/draft.blade.php
@extends('layouts.dashboard')
@section('title','Draft')
@section('content-header')
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Draft</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">VBES</a></li>
          <li class="breadcrumb-item active">Draft</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
@endsection
@section('content')
      <div class="row">
        <div class="col-md-3">

          @include('dashboard.partials.folder')

        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="card card-primary card-outline" id = "ajaxPagi">
          @if($data->count())
            <div class="card-header">
              <h3 class="card-title table-name">Draft</h3>
              <div class="card-tools">
                <div class="input-group input-group-sm">
                  <input type="text" class="form-control mail-search-input" placeholder="Search Mail">
                  <div class="input-group-append">
                    <div class="btn btn-primary">
                      <i class="fas fa-search"></i>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
              <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                  <a href="javascript:;" title = "Trash" class="btn btn-default btn-sm btn-delete">
                    <i class="far fa-trash-alt"></i>
                  </a>
                  <a href="javascript:;" title = "Reply" class="btn btn-default btn-sm btn-main-reply">
                    <i class="fas fa-reply"></i>
                  </a>
                  <a href="#" title = "Share" class="btn btn-default btn-sm">
                    <i class="fas fa-share"></i>
                  </a>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm">
                  <i class="fas fa-sync-alt"></i>
                </button>
                <div class="float-right">

                                      {{ $data->links() }}
                  </div>
                  <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
              </div>
              <div class="table-responsive mailbox-messages">
                <table class="table table-hover table-striped">
                  <tbody>
                    {{Form::open(['url' => route('draft.delete'),'class' => 'delete-record-form'])}}
                    @php $view_click_id = 0; @endphp
                    @foreach($data as $record)
                    @php $view_click_id++; @endphp
                  <tr>
                    <td>
                      <div class="icheck-primary">
                        {{Form::checkbox('del_record[]',$record->id,false,['id' => $record->id,'class' => 'checkbox-record','data-mail_id' => $record->mail_id,'data-mail_type' => 'out'])}}
                        <label for="{{ $record->id }}" data-select_id = "{{$view_click_id}}"></label>
                      </div>
                    </td>
                    <td class="mailbox"><a href="{{ route('draft.imp',$record->id) }}" title = "{{ $record->isImp == 'yes' ? 'Remove from important' : 'Add to important' }}" data-imp_make_id = "{{$view_click_id}}">
                      <i class="fas fa-star text-{{ $record->isImp == 'yes' ? 'warning' : 'gray-dark' }}"></i></a>
                    </td>
                    <td class="mailbox-name">{{ $record->mail->receiver_id ?? "no user name" }}</a>
                    </td>
                      <td class="mailbox-subject">
                      <b>
                        @if($record->mail->subject != null)
                        {{ Illuminate\Support\Str::limit($record->mail->subject,30,'...') }}
                        @else
                        {!! Illuminate\Support\Str::words($record->mail->message,2,'...') !!}
                        @endif
                      </b>
                      </td>
                      <td>
                        <a href="{{route('draft.show',$record->id)}}" data-view_click_id = "{{$view_click_id}}" title = "Read Mail">
                        <i class="fas fa-eye"></i></a>
                      </td>
                    <td class="mailbox-date">{{$record->mail->created_at->diffForHumans()}}</td>
                  </tr>
                  @endforeach
                  {{Form::close()}}
                  </tbody>
                </table>
                <!-- /.table -->
              </div>
              <!-- /.mail-box-messages -->
            </div>
            <!-- /.card-body -->
            <div class="card-footer p-0">
              <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                  <i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                  <a href="javascript:;" title = "Trash" class="btn btn-default btn-sm btn-delete">
                    <i class="far fa-trash-alt"></i>
                  </a>
                  <a href="javascript:;" title = "Reply" class="btn btn-default btn-sm btn-main-reply">
                    <i class="fas fa-reply"></i>
                  </a>
                  <a href="#" title = "Share" class="btn btn-default btn-sm">
                    <i class="fas fa-share"></i>
                  </a>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm">
                  <i class="fas fa-sync-alt"></i>
                </button>
                <div class="float-right">
                  {{ $data->links() }}
                  <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
              </div>
            </div>
          @else
            <div class="card-body p-0">
              <div class="mailbox-controls">
                <div class="table-responsive mailbox-messages">
                  <div class="bg-info text-center p-5">
                      <h1>Empty</h1>
                  </div>
                </div>
              </div>
            </div>
          @endif
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
@endsection

@section('scripts')
<script>
//
</script>
@endsection

resources/views/dashboard/imp.blade.php
@extends('layouts.dashboard')
@section('title','Important')
@section('content-header')
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Important</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">VBES</a></li>
          <li class="breadcrumb-item active">Important</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
@endsection
@section('content')
      <div class="row">
        <div class="col-md-3">

          @include('dashboard.partials.folder')

        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="card card-primary card-outline">
          @if($data->count())
            <div class="card-header">
              <h3 class="card-title table-name">Important</h3>

              <div class="card-tools">
                <div class="input-group input-group-sm">
                  <input type="text" class="form-control mail-search-input" placeholder="Search Mail">
                  <div class="input-group-append">
                    <div class="btn btn-primary">
                      <i class="fas fa-search"></i>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0 search-pagination-part">
              <div class="mailbox-controls ">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                  <a href="javascript:;" title = "Trash" class="btn btn-default btn-sm btn-delete">
                    <i class="far fa-trash-alt"></i>
                  </a>
                  <a href="javascript:;" title = "Reply" class="btn btn-default btn-sm btn-main-reply">
                    <i class="fas fa-reply"></i>
                  </a>
                  <a href="#" title = "Share" class="btn btn-default btn-sm">
                    <i class="fas fa-share"></i>
                  </a>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm">
                  <i class="fas fa-sync-alt"></i>
                </button>
                <div class="float-right pagination-link">
                  {{ $data->links() }}
                  </div>
                  <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
              </div>
              <div class="table-responsive mailbox-messages">
                <table class="table table-hover table-striped">
                  <tbody>
{{Form::open(['url' => route('imp.delete'),'class' => 'delete-record-form'])}}
    @php $view_click_id = 0; @endphp
                  @foreach($data as $key => $record)
                  @php $view_click_id++; @endphp
                  <tr>
                    <td>
                    @php
                      if($record->trash_id != null){
                        $imp_data = DB::table('mails')->where('id',$record->trash->mail_id)->first();
                        $user_name =  ($record->trash->isInbox == 'yes') ? $imp_data->sender_id : $imp_data->receiver_id ;
                        $mail_type = ($record->trash->isInbox == 'yes') ? 'in' : 'out';
                      }
                      if ($record->draft_id != null) {
                        $imp_data = DB::table('mails')->where('id',$record->draft->mail_id)->first();
                        $user_name = $imp_data->receiver_id;
                        $mail_type = 'out';

                      }
                      if ($record->inbox_id != null) {
                        $imp_data = DB::table('mails')->where('id',$record->inbox->mail_id)->first();
                        $user_name = $imp_data->sender_id;
                        $mail_type = 'in';
                      }
                      if ($record->outbox_id != null) {
                        $imp_data = DB::table('mails')->where('id',$record->outbox->mail_id)->first();
                        $user_name = $imp_data->receiver_id;
                        $mail_type = 'out';
                      }
                     @endphp
                      <div class="icheck-primary">
                        {{Form::checkbox('del_record[]',$record->id,false,['id' => $record->id,'class' => 'checkbox-record','data-mail_id' => $imp_data->id,'data-mail_type' => $mail_type])}}
                        <label for="{{ $record->id }}" data-select_id = "{{$view_click_id}}"></label>
                      </div>
                    </td>
                    <td class="mailbox-name">
                      {{ $user_name ?? "*__ no-user-name __*" }}
                    </td>
                      <td class="mailbox-subject"><b>
                        @if($imp_data->subject != null)
                        {{ Illuminate\Support\Str::limit($imp_data->subject,30,'...') }}
                        @else
                        {!! Illuminate\Support\Str::words($imp_data->message,2,'...') !!}
                        @endif
                        </b>
                      </td>
                      <td class="mailbox-attachment">
{{--                         @if($attachments->count() > 0)
                        <i class="fas fa-paperclip"></i>
                        @endif --}}
                        @if(count($attachments[$key]) > 0)
                        <i class="fas fa-paperclip"></i>
                        @endif
                      </td>
                      <td>
                        <a href="{{route('imp.show',$record->id)}}" data-view_click_id = "{{$view_click_id}}" title = "Read Mail">
                        <i class="fas fa-eye"></i></a>
                      </td>
                    <td class="mailbox-date">{{Carbon\Carbon::parse($imp_data->created_at)->diffForHumans()}}</td>
                  </tr>
                  @endforeach
{{Form::close()}}

                  </tbody>
                </table>
                <!-- /.table -->
              </div>
              <!-- /.mail-box-messages -->
            </div>
            <!-- /.card-body -->
            <div class="card-footer p-0">
              <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                  <i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                  <a href="javascript:;" title = "Trash" class="btn btn-default btn-sm btn-delete">
                    <i class="far fa-trash-alt"></i>
                  </a>
                  <a href="#" title = "Reply" class="btn btn-default btn-sm btn-main-reply">
                    <i class="fas fa-reply"></i>
                  </a>
                  <a href="#" title = "Share" class="btn btn-default btn-sm">
                    <i class="fas fa-share"></i>
                  </a>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm">
                  <i class="fas fa-sync-alt"></i>
                </button>
                <div class="float-right pagination-link">
                  {{ $data->links() }}
                  <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
              </div>
            </div>
          @else
            <div class="card-body p-0">
              <div class="mailbox-controls">
                <div class="table-responsive mailbox-messages">
                  <div class="bg-info text-center p-5">
                      <h1>Empty</h1>
                  </div>
                </div>
              </div>
            </div>
          @endif
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
@endsection
@section('scripts')
<script>
  countapi.hit('vbes.test', "mail").then((result) => { 
    // alert("you  have visited this page "+result.value);
  });
</script>
@endsection

resources/views/dashboard/search_result_preview.blade.php
  @if($data->count())
          {{ dd($data) }}
            <!-- /.card-header -->
            <div class="card-body p-0">
              <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                  <a href="javascript:;" title = "Trash" class="btn btn-default btn-sm btn-delete">
                    <i class="far fa-trash-alt"></i>
                  </a>
                  <a href="javascript:;" title = "Reply" class="btn btn-default btn-sm btn-main-reply">
                    <i class="fas fa-reply"></i>
                  </a>
                  <a href="#" title = "Share" class="btn btn-default btn-sm">
                    <i class="fas fa-share"></i>
                  </a>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm">
                  <i class="fas fa-sync-alt"></i>
                </button>
                <div class="float-right">

                                      {{ $data->links() }}
                  </div>
                  <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
              </div>
              <div class="table-responsive mailbox-messages">
                <table class="table table-hover table-striped">
                  <tbody>
{{Form::open(['url' => route('inbox.delete'),'class' => 'delete-record-form'])}}
@php $view_click_id = 0; @endphp
                  @foreach($data as $record)
                  @php $view_click_id++; @endphp
                  <tr>
                    <td>
                      <div class="icheck-primary">
                        {{Form::checkbox('del_record[]',$record->id,false,['id' => $record->id,'class' => 'checkbox-record','data-mail_id' => @$record->mail_id,'data-mail_type' => 'in'])}}
                        <label for="{{ $record->id }}" data-select_id = "{{$view_click_id}}"></label>
                      </div>
                    </td>
                    <td class="mailbox-name">{{ $record->sender_id }}
                    </td>
                      <td class="mailbox-subject"><b>
                        @if($record->mail->subject != null)
                        {{ Illuminate\Support\Str::limit($record->subject,80,'...') }}
                        @else
                        {!! Illuminate\Support\Str::words($record->message,2,'...') !!}
                        @endif
                      </b>
                      </td>
                      <td class="mailbox-attachment">                        
                        @if($attachments->count() > 0)
                        <i class="fas fa-paperclip"></i>
                        @endif
                      </td>
                      <td>
                        <a href="{{route('inbox.show',$record->id)}}" data-view_click_id = "{{$view_click_id}}" title = "Read Mail">
                        <i class="fas fa-eye"></i></a>
                      </td>
                    <td class="mailbox-date">{{$record->created_at->diffForHumans()}}</td>
                  </tr>
                  @endforeach
{{Form::close()}}

                  </tbody>
                </table>
                <!-- /.table -->
              </div>
              <!-- /.mail-box-messages -->
            </div>
            <!-- /.card-body -->
            <div class="card-footer p-0">
              <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                  <i class="far fa-square"></i>
                </button>
                <div class="btn-group">
                  <a href="javascript:;" title = "Trash" class="btn btn-default btn-sm btn-delete">
                    <i class="far fa-trash-alt"></i>
                  </a>
                  <a href="javascript:;" title = "Reply" class="btn btn-default btn-sm btn-main-reply">
                    <i class="fas fa-reply"></i>
                  </a>
                  <a href="#" title = "Share" class="btn btn-default btn-sm">
                    <i class="fas fa-share"></i>
                  </a>
                </div>
                <!-- /.btn-group -->
                <button type="button" class="btn btn-default btn-sm">
                  <i class="fas fa-sync-alt"></i>
                </button>
                <div class="float-right">
                  {{ $data->links() }}
                  <!-- /.btn-group -->
                </div>
                <!-- /.float-right -->
              </div>
            </div>
          @else
            <div class="card-body p-0">
              <div class="mailbox-controls">
                <div class="table-responsive mailbox-messages">
                  <div class="bg-info text-center p-5">
                      <h1>Empty</h1>
                  </div>
                </div>
              </div>
            </div>
          @endif

resources/views/dashboard/test.blade.php
{{dd($results)}}
@foreach($results as $key => $result)
  {{ $result }}
@endforeach