routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function(){ 
    return redirect()->route('login');
})
->name('landing');
Route::get('/chatbox',function(){
    return view('front.chatBox');
})->name('chatbox');
// Route::post('/botman', [App\Http\Controllers\BotManController::class,'handle']);
Route::match(['get', 'post'], '/botman', [App\Http\Controllers\BotManController::class,'handle'])->name('botman');

Route::get('login/locked', [App\Http\Controllers\Auth\LoginController::class,'locked'])->middleware('auth')->name('login.locked');
Route::post('login/locked', [App\Http\Controllers\Auth\LoginController::class,'unlock'])->name('login.unlock');

// Route::get('/', [App\Http\Controllers\FrontController::class,'index'])->name('landing');
Route::get('about', [App\Http\Controllers\FrontController::class,'about'])->name('about');
Route::get('team', [App\Http\Controllers\FrontController::class,'team'])->name('team');
Route::get('/service', [App\Http\Controllers\FrontController::class,'service'])->name('service');
Route::get('/chatbot', [App\Http\Controllers\FrontController::class,'chatbot'])->name('chatbot');
Route::get('/voice_chatbot', [App\Http\Controllers\FrontController::class,'voiceChatbot'])->name('voiceChatbot');
Route::get('/contact', [App\Http\Controllers\FrontController::class,'contact'])->name('contact');
Route::get('/faq', [App\Http\Controllers\FrontController::class,'faq'])->name('faq');
Route::get('/blog', [App\Http\Controllers\FrontController::class,'blog'])->name('blog');
Route::get('/blog_detail', [App\Http\Controllers\FrontController::class,'blogDetail'])->name('blogDetail');
Route::get('/privacy', [App\Http\Controllers\FrontController::class,'privacy'])->name('privacy');
Route::get('/terms', [App\Http\Controllers\FrontController::class,'terms'])->name('terms');
Route::post('/contact', [App\Http\Controllers\FrontController::class,'contactStore'])->name('contact-post');
Route::get('/read-aloud', [App\Http\Controllers\FrontController::class,'readAloud'])->name('read-aloud');



Route::group(['prefix'=>'/','middleware'=>['auth'],'namespace'=>'App\Http\Controllers'],function(){
/* Route::get('/dashboard', function () {
    return view('dashboard.dashboard');
})->name('dashboard'); */

Route::patch('/change-pwd','HomeController@changePassword')->name('change-password');
Route::patch('/delete-account','HomeController@deleteAccount')->name('delete-account');
Route::patch('/update-me','HomeController@updateMe')->name('update-me');
Route::patch('/screen-lock','HomeController@screenLock')->name('screenLock');// screen-lock

Route::group(['prefix'=>'mail'],function(){
Route::resource('inbox','InboxController')->only(['index','show']);
Route::resource('sent','OutboxController')->only(['index','show']);
Route::resource('draft','DraftController')->only(['index','show']);
Route::resource('trash','TrashController')->only(['index','show']);
Route::resource('imp','ImportantController')->only(['index','show']);
Route::resource('/','MailController',
	['names' => array(
		// 'show' => 'mail.show',
		'edit' => 'mail.edit',
		'store' => 'mail.store')])
->except(['update','destroy','index','create','show']);
Route::get('/compose','MailController@compose')->name('mail.compose');
Route::delete('inbox/delete/{id?}','InboxController@deleteRecord')->name('inbox.delete');
Route::delete('sent/delete/{id?}','OutboxController@deleteRecord')->name('sent.delete');
Route::delete('trash/delete{id?}','TrashController@deleteRecord')->name('trash.delete');
Route::delete('draft/delete/{id?}','DraftController@deleteRecord')->name('draft.delete');
Route::delete('imp/delete/{id?}','ImportantController@deleteRecord')->name('imp.delete');
Route::get('trash/{id}/make-imp','TrashController@makeItImp')->name('trash.imp');
Route::get('draft/{id}/make-imp','DraftController@makeItImp')->name('draft.imp');
Route::get('inbox/{id}/make-imp','InboxController@makeItImp')->name('inbox.imp');
Route::get('sent/{id}/make-imp','OutboxController@makeItImp')->name('sent.imp');
Route::get('mail/{dir}/{file_name}/dowload-attachment','MailController@attachDownload')->name('download-attach');
Route::get('mail/{dir}/{file_name}/display-attachment','MailController@attachDisplay')->name('display-attach');
Route::get('{mail_id}/{mail_type}/reply','MailController@reply')->name('mail.reply');
Route::get('mail-user/search', 'MailController@mailUserSearch')->name('navbar-search');
Route::get('/search', 'MailController@mailSearch')->name('mail-search');
Route::get('{user_id}/compose','MailController@mailSendBySearch')->name('mail-Send-by-search');
Route::get('/created_at', 'MailController@createDiffForHumans')->name('created_at');
Route::get('/attachment', 'MailController@attachmentsByMailId')->name('isExistsAttachment');
Route::get('subject/create', 'MailController@subjectCreate')->name('subjectCreate');
});
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//for admin
Route::group(['prefix' => 'admin','middleware' => ['auth','admin'],'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/dashboard', 'Homecontroller@admin')->name('admin');
    Route::resource('user', 'UserController');// for user manager
    Route::get('/user/{id}/change-password','UserController@showPasswordChangeForm')->name('change-pwd');
    Route::patch('/user/{id}/change-password','UserController@updatePassword')->name('user-update-password');
    Route::get('/user/status-change/{id}/{status}','UserController@changeStatus')->name('user-change-status');
});

//for normal user
Route::group(['prefix' => '/','middleware' => ['auth','user'],'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'user'])->middleware('auth.lock')->name('user');
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'user'])->middleware('auth.lock')->name('dashboard');
});

// for chatbot

// Route::match(['get', 'post'], '/chatbot/botman', [App\Http\Controllers\BotManController::class, 'handle']);
/* Route::post('/chatbot/botman',function(){
    app('botman')->listen();
}); */

resources/views/dashboard/partials/folder.blade.php
          @if(request()->getRequestUri() == '/mail/compose')
            <a href="{{ route('inbox.index') }}" class="btn btn-primary btn-block mb-3">Back to Inbox</a>
          @else
          <a href="{{ route('mail.compose') }}" class="btn btn-primary btn-block mb-3" data-turbolinks="false">Compose</a>
          @endif
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Folders</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="card-body p-0">
              <ul class="nav nav-pills flex-column">
                <li class="nav-item ">
                  <a href="{{ route('inbox.index') }}" class="nav-link {{(request()->getRequestUri() == '/mail/inbox') ? 'text-primary' : ''}}">
                    <i class="fas fa-inbox"></i> Inbox
                    @if(auth()->user()->unReadNotifications()->where('data->notification_for','user')->count())
                      <span class="badge bg-primary float-right">{{auth()->user()->unReadNotifications()->where('data->notification_for','user')->count()}}</span>
                    @endif
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{ route('sent.index') }}" class="nav-link {{(request()->getRequestUri() == '/mail/sent') ? 'text-primary' : ''}}">
                    <i class="far fa-paper-plane"></i> Sent
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{ route('draft.index') }}" class="nav-link {{(request()->getRequestUri() == '/mail/draft') ? 'text-primary' : ''}}">
                    <i class="far fa-file-alt"></i> Drafts
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{ route('trash.index') }}" class="nav-link {{(request()->getRequestUri() == '/mail/trash') ? 'text-primary' : ''}}">
                    <i class="far fa-trash-alt"></i> Trash
                  </a>
                </li>
              </ul>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Label</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="card-body p-0">
              <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                  <a href="{{ route('imp.index') }}" class="nav-link {{(request()->getRequestUri() == '/mail/imp') ? 'text-primary' : ''}}">
                    <i class="far fa-star text-danger"></i>
                    Important
                  </a>
                </li>
              </ul>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->

resources/views/dashboard/partials/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VBES | @yield('title')</title>
    <link href="{{ asset('img/favicon.png') }}" rel="icon">
    @if(is_connected())
    <script src="{{ asset('js/annyangJS/annyang.min.js') }}" class = 'voiceEnabled'></script>
    @endif
	<script src="https://code.responsivevoice.org/responsivevoice.js?key=auvTMQpf"></script> 

    <!-- <script src="{{ asset('js/responsiveVoice/responsiveVoice.js') }}"></script> -->
    {{-- <script src="{{ asset('js/turbo.js') }}" data-turbolinks-suppress-warning></script> --}}
    <link rel="stylesheet" href="{{ mix('css/dashboard.css') }}">
    @yield('styles')
</head>

resources/views/dashboard/partials/notify.blade.php
@if($message = Session::get('error'))
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" ria-hidden="true">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif
@if($message = Session::get('success'))
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" ria-hidden="true">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif
@if($message = Session::get('info'))
    <div class="alert alert-info alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" ria-hidden="true">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif
@if($message = Session::get('warning'))
    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" ria-hidden="true">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

resources/views/dashboard/partials/scripts.blade.php
<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>
<script src="{{ mix('js/dashboard.js') }}"></script>

resources/views/dashboard/partials/sidebar.blade.php
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4  sidebar-dark navbar-navy">
        <!-- Brand Logo -->
        <a href="{{ route('dashboard') }}" class="brand-link navbar-navy">
            <img src="{{ asset('img/favicon.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: 1; size : 45px;">
            <span class="brand-text font-weight-bold" style = "color:#228855; opacity : 1; margin-left : -6px;text-size : 25px;">BES</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="pull-left image">
                @if(isset(request()->user()->userInfo['photo']) && !empty(request()->user()->userInfo['photo']))
                    <img src="{{asset('uploads/user/'.request()->user()->userInfo['photo'])}}" class="img-circle elevation-2" alt="User Image" style="height: 45px; width: 45px;"/>
                @else
                    <img src="{{asset('img/avatar.png')}}"  class="img-circle elevation-2" alt="User Image" style="height: 60px; width: 60px;"/>
                @endif
                </div>
                <div class="pull-left info">
                    <a href="javascript:;" class="d-block"> {{ request()->user()->name   }}</a>
                    @if(is_connected())
                        <a href="javascript:;" class = "text-xs"><i class="fa fa-circle text-success"></i> Online</a>
                    @else
                        <a href="javascript:;" class = "text-xs"><i class="fa fa-circle text-secondary"></i> Offline</a>
                    @endif
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2 flex-column nav-compact">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item">
                        <a href="{{ route('dashboard') }}" title = "Dashboard" class="nav-link {{(request()->getRequestUri() == '/dashboard') ? 'active' : ''}}">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                Dashboard
                            </p>
                        </a>
                    </li>
                    <li class="nav-item menu-open">
                        <a href="Javascript:;" title = "Mail" class="nav-link ">
                            <i class="nav-icon far fa-envelope"></i>
                            <p> Mail
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{ route('mail.compose') }}" data-turbolinks="false" title = "Compose" class="nav-link {{(request()->getRequestUri() == '/mail/create') ? 'active' : ''}}">
                                    <i class="far fa-edit nav-icon"></i>
                                    <p>Compose</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('inbox.index') }}" title = "Inbox" class="nav-link {{(request()->getRequestUri() == '/mail/inbox') ? 'active' : ''}}">
                                    <i class="fas fa-inbox nav-icon"></i>
                                    <p>Inbox</p>
                                    @if(auth()->user()->unReadNotifications()->where('data->notification_for','user')->count())
                                <span class="badge badge-info right">
                            {{auth()->user()->unReadNotifications()->where('data->notification_for','user')->count()}}</span>
                            @endif
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('sent.index') }}" title = "Sent" class="nav-link {{(request()->getRequestUri() == '/mail/sent') ? 'active' : ''}}">
                                    <i class="far fa-paper-plane nav-icon"></i>
                                    <p>Sent</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="javascript:;" title = "More" class="nav-link nav_more_btn">
                                    <i class="fa fa-caret-down nav-icon"></i>
                                    <p> More
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview d-none to_be_toggle">
                                    <li class="nav-item">
                                        <a href="{{ route('draft.index') }}" title = "Draft" class="nav-link {{(request()->getRequestUri() == '/mail/draft') ? 'active' : ''}}">
                                            <i class="far fa-file-alt nav-icon"></i>
                                            <p>Draft</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ route('trash.index') }}" title = "Trash" class="nav-link {{(request()->getRequestUri() == '/mail/trash') ? 'active' : ''}}">
                                            <i class="far fa-trash-alt nav-icon"></i>
                                            <p>Trash</p>
                                        </a>
                                    </li>
                                    <li class="nav-header mt-1 pt-0">Label</li>
                                    <li class="nav-item">
                                        <a href="{{ route('imp.index') }}" title = "Important Mails" class="nav-link {{(request()->getRequestUri() == '/mail/imp') ? 'active' : ''}}">
                                            <i class="far fa-star nav-icon"></i>
                                            <p>Important</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    @if(auth()->user()->role == 'admin')
                    <li class="nav-header mt-1 pt-0">Manager</li>
                    <li class="nav-item">
                        <a href="Javascript:;" title = "User Manager" class="nav-link ">
                            <i class="nav-icon fa fa-users"></i>
                            <p> User Manager
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{ route('user.create') }}" title = "Sent" class="nav-link {{(request()->getRequestUri() == '/admin/user/create') ? 'active' : ''}}">
                                    <i class="fas fa-user-plus nav-icon"></i>
                                    <p>Add User</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('user.index') }}" title = "Sent" class="nav-link {{(request()->getRequestUri() == '/admin/user') ? 'active' : ''}}">
                                    <i class="far fa-eye nav-icon"></i>
                                    <p>List User</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    {{-- <li class="nav-item">
                        <a href="Javascript:;" title = "User Manager" class="nav-link ">
                            <i class="nav-icon fas fa-blog"></i>
                            <p> Blog Manager
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{ route('sent.index') }}" title = "Sent" class="nav-link {{(request()->getRequestUri() == '/mail/sent') ? 'active' : ''}}">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Add Blog</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('sent.index') }}" title = "Sent" class="nav-link {{(request()->getRequestUri() == '/mail/sent') ? 'active' : ''}}">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>List Blog</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="Javascript:;" title = "User Manager" class="nav-link ">
                            <i class="nav-icon fa fa-file"></i>
                            <p> Page Manager
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{ route('sent.index') }}" title = "Sent" class="nav-link {{(request()->getRequestUri() == '/mail/sent') ? 'active' : ''}}">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Add Page</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('sent.index') }}" title = "Sent" class="nav-link {{(request()->getRequestUri() == '/mail/sent') ? 'active' : ''}}">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>List Page</p>
                                </a>
                            </li>
                        </ul>
                    </li> --}}
                    @endif
                    <li class="nav-header">Profile</li>
                    <li class="nav-item">
                        <a href="javascript:;" title = "Update Profile" class="nav-link" id="updateProfileBtn">
                            <i class="nav-icon fas fa-user-edit"></i>
                            <p>
                                Update Profile
                            </p>
                        </a>
                    </li>
                    <li class="nav-header">Settings</li>
                    <li class="nav-item">
                        <a href="javascript:;" title ="Change Password" class="nav-link" id="changePasswordBtn">
                            <i class="nav-icon far fa-edit"></i>
                            <p>
                                Change Password
                            </p>
                        </a>
                    </li>
                    @if(auth()->user()->role == 'user')
                    <li class="nav-item">
                        <a href="javascript:;" title = "Delete Account" class="nav-link" id="deleteAccountBtn">
                            <i class="nav-icon fas fa-user-minus"></i>
                            <p>
                                Delete Account
                            </p>
                        </a>
                    </li>
                    @endif
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>