routes/web.php
<?php

use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function(){ 
    return redirect()->route('login');
})
->name('landing');
Route::get('/chatbox',function(){
    return view('front.chatBox');
})->name('chatbox');
// Route::post('/botman', [App\Http\Controllers\BotManController::class,'handle']);
Route::match(['get', 'post'], '/botman', [App\Http\Controllers\BotManController::class,'handle'])->name('botman');

Route::get('login/locked', [App\Http\Controllers\Auth\LoginController::class,'locked'])->middleware('auth')->name('login.locked');
Route::post('login/locked', [App\Http\Controllers\Auth\LoginController::class,'unlock'])->name('login.unlock');

// Route::get('/', [App\Http\Controllers\FrontController::class,'index'])->name('landing');
Route::get('about', [App\Http\Controllers\FrontController::class,'about'])->name('about');
Route::get('team', [App\Http\Controllers\FrontController::class,'team'])->name('team');
Route::get('/service', [App\Http\Controllers\FrontController::class,'service'])->name('service');
Route::get('/chatbot', [App\Http\Controllers\FrontController::class,'chatbot'])->name('chatbot');
Route::get('/voice_chatbot', [App\Http\Controllers\FrontController::class,'voiceChatbot'])->name('voiceChatbot');
Route::get('/contact', [App\Http\Controllers\FrontController::class,'contact'])->name('contact');
Route::get('/faq', [App\Http\Controllers\FrontController::class,'faq'])->name('faq');
Route::get('/blog', [App\Http\Controllers\FrontController::class,'blog'])->name('blog');
Route::get('/blog_detail', [App\Http\Controllers\FrontController::class,'blogDetail'])->name('blogDetail');
Route::get('/privacy', [App\Http\Controllers\FrontController::class,'privacy'])->name('privacy');
Route::get('/terms', [App\Http\Controllers\FrontController::class,'terms'])->name('terms');
Route::post('/contact', [App\Http\Controllers\FrontController::class,'contactStore'])->name('contact-post');
Route::get('/read-aloud', [App\Http\Controllers\FrontController::class,'readAloud'])->name('read-aloud');



Route::group(['prefix'=>'/','middleware'=>['auth'],'namespace'=>'App\Http\Controllers'],function(){
/* Route::get('/dashboard', function () {
    return view('dashboard.dashboard');
})->name('dashboard'); */

Route::patch('/change-pwd','HomeController@changePassword')->name('change-password');
Route::patch('/delete-account','HomeController@deleteAccount')->name('delete-account');
Route::patch('/update-me','HomeController@updateMe')->name('update-me');
Route::patch('/screen-lock','HomeController@screenLock')->name('screenLock');// screen-lock

Route::group(['prefix'=>'mail'],function(){
Route::resource('inbox','InboxController')->only(['index','show']);
Route::resource('sent','OutboxController')->only(['index','show']);
Route::resource('draft','DraftController')->only(['index','show']);
Route::resource('trash','TrashController')->only(['index','show']);
Route::resource('imp','ImportantController')->only(['index','show']);
Route::resource('/','MailController',
	['names' => array(
		// 'show' => 'mail.show',
		'edit' => 'mail.edit',
		'store' => 'mail.store')])
->except(['update','destroy','index','create','show']);
Route::get('/compose','MailController@compose')->name('mail.compose');
Route::delete('inbox/delete/{id?}','InboxController@deleteRecord')->name('inbox.delete');
Route::delete('sent/delete/{id?}','OutboxController@deleteRecord')->name('sent.delete');
Route::delete('trash/delete{id?}','TrashController@deleteRecord')->name('trash.delete');
Route::delete('draft/delete/{id?}','DraftController@deleteRecord')->name('draft.delete');
Route::delete('imp/delete/{id?}','ImportantController@deleteRecord')->name('imp.delete');
Route::get('trash/{id}/make-imp','TrashController@makeItImp')->name('trash.imp');
Route::get('draft/{id}/make-imp','DraftController@makeItImp')->name('draft.imp');
Route::get('inbox/{id}/make-imp','InboxController@makeItImp')->name('inbox.imp');
Route::get('sent/{id}/make-imp','OutboxController@makeItImp')->name('sent.imp');
Route::get('mail/{dir}/{file_name}/dowload-attachment','MailController@attachDownload')->name('download-attach');
Route::get('mail/{dir}/{file_name}/display-attachment','MailController@attachDisplay')->name('display-attach');
Route::get('{mail_id}/{mail_type}/reply','MailController@reply')->name('mail.reply');
Route::get('mail-user/search', 'MailController@mailUserSearch')->name('navbar-search');
Route::get('/search', 'MailController@mailSearch')->name('mail-search');
Route::get('{user_id}/compose','MailController@mailSendBySearch')->name('mail-Send-by-search');
Route::get('/created_at', 'MailController@createDiffForHumans')->name('created_at');
Route::get('/attachment', 'MailController@attachmentsByMailId')->name('isExistsAttachment');
Route::get('subject/create', 'MailController@subjectCreate')->name('subjectCreate');
});
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//for admin
Route::group(['prefix' => 'admin','middleware' => ['auth','admin'],'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/dashboard', 'Homecontroller@admin')->name('admin');
    Route::resource('user', 'UserController');// for user manager
    Route::get('/user/{id}/change-password','UserController@showPasswordChangeForm')->name('change-pwd');
    Route::patch('/user/{id}/change-password','UserController@updatePassword')->name('user-update-password');
    Route::get('/user/status-change/{id}/{status}','UserController@changeStatus')->name('user-change-status');
});

//for normal user
Route::group(['prefix' => '/','middleware' => ['auth','user'],'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'user'])->middleware('auth.lock')->name('user');
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'user'])->middleware('auth.lock')->name('dashboard');
});

// for chatbot

// Route::match(['get', 'post'], '/chatbot/botman', [App\Http\Controllers\BotManController::class, 'handle']);
/* Route::post('/chatbot/botman',function(){
    app('botman')->listen();
}); */

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Traits\LockableTrait;
class User extends Authenticatable
{
    use HasFactory, Notifiable;
    use LockableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'lockout_time','role','status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getUpdatePassword(){
        return [
            'current_password' => ['required','string','min:8'],
            'password' => ['required','string','min:8','confirmed']
        ];
    }

    public  function getUpdateRule(){
        return [
            'name' => 'required|string|max:50',
            'dob' => 'nullable|date',
            'photo' => 'sometimes|image|max:5000',
            'gender' => 'sometimes|in:male,female,other'
        ];
    }

    public function userInfo(){
        return $this->hasOne('\App\Models\UserInfo','user_id','id');
    }

    public function getRules(){
        return [
            'name' => 'required|string|max:50',
            'email' =>'required|email|unique:users,email',
            'password' => ['required','string','min:8','confirmed'],
//            'user_id'=>'required|exists:users,id',
            'dob' => 'nullable|date',
            'photo' => 'sometimes|image|max:5000',
            'gender' => 'sometimes|in:male,female,other',
            'role' => 'required|in:user',
            'status' => 'required|in:active,inactive'
        ];
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\UserInfo;
use Illuminate\Http\Request;
use Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $user,$userInfo;
    public function __construct(User $user,UserInfo $userInfo)
    {
        $this->user = $user;
        $this->userInfo = $userInfo;
    }
    private function validateId($id){
        $this->user = $this->user->find($id);
        if(!$this->user){
            request()->session()->flash('error','Sorry!, user does not exists');
            return  redirect()-route('user.index');
        }
    }
    public function index()
    {
        $all_users = $this->user->where('id','!=',request()->user()->id)->orderBy('id','DESC')->get();
        $role = 'user';
        return view('admin.user.index')
        ->with('role',$role)
        ->with('all_users',$all_users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate($this->user->getRules());
//        dd($request->all());
        $data = $request->all();
        $data['password'] = Hash::make($data['password']);
        $this->user->fill($data);
        $status = $this->user->save($data);
        if($status){
            $data['user_id'] = $this->user->id;
            if($request->photo){
                $file_name = imageUpload($request->photo,'user',env('PROFILE_IMG_SIZE','200x200'));
                if($image_name){
                    $data['photo'] = $file_name;
                }
            }
            $this->userInfo->fill($data);
            $this->userInfo->save();
            $request->session()->flash('success','User Created successfully.');
        }else{
            $request->session()->flash('error','Sorry!, error while creating user');

        }
//         dd($this->user);
        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($user)
    {
        if ($user == 'returnBack') {
            $notifications = auth()->user()->notifications()
            ->where('data->notification_for','admin')
                    ->get();
            if($notifications->count()){
                foreach ($notifications as $notification) {
                    $notification->markAsRead();
                }
            }
            $request->session()->flash('success','All notifications mark as read successfully.');
            return redirect()->back();
        }else{
            $all_users = $this->user->where('email',$user)->get();
            $user = $this->user->where('email',$user)->first();
            $role = 'admin';
            $notification = auth()->user()->notifications()->where('data->notification_for','admin')->where('data->email',$user->email)
            ->first();
            if($notification){
                $notification->markAsRead();
            }
            return view('admin.user.index')
            ->with('role',$role)
            ->with('user',$user->name)
            ->with('all_users',$all_users);  
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->validateId($id);
        return view('admin.user.form')->with('user_detail',$this->user);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validateId($id);
        $request->validate($this->user->getUpdateRule());
        $data = $request->all();
        $this->user->fill($data);
        $status = $this->user->save();
        if($status){
            if($request->photo){
                $image_name = imageUpload($request->photo,'user',env('UserImageSize','200x200'));
                if($image_name){
                    if (isset($this->user->userInfo->image) && $this->user->userInfo->image != null) {
                        deleteImage($this->user->userInfo->image,'user');
                    }
                    $data['photo'] = $image_name;
                }
            }
            if($this->user->userInfo == null){
                $data['user_id'] = $this->user->id;
                $this->user->userInfo = new UserInfo();

            }
            $this->user->userInfo->fill($data);
            $this->user->userInfo->save();
            $request->session()->flash('success','User updated successfully.');
        }else{
            $request->session()->flash('error','Sorry!, error while updating user');

        }
        // return redirect()->route('user.show',$this->user->role);
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->validateId($id);
        $image = $this->userInfo->image;
        $status = $this->user->delete();
        if($status){
            if($image != null){
                deleteImage($image->image, 'user');
            }
            request()->session()->flash('success','user successfully deleted');
        }else{
            request()->session()->flash('error','Sorry!, user does not exists');
        }
        return redirect()->back();
    }

    public function changeStatus(Request $request){
        $this->validateId($request->id);
        if($this->user->status == 'active') {
            $this->user->status = 'inactive';
        }else{
            $this->user->status = 'active';
        }
        $status = $this->user->save();
        if($status){
            $request->session()->flash('success','user status changed successfully.');
        }else{
            $request->session()->flash('error','Sorry!, error while changing user status');
        }
            return redirect()->back();
    }

    public function showPasswordChangeForm($id){
        $this->validateId($id);
        return view('admin.user.password-change')->with('user_data',$this->user);
    }
    public function updatePassword(Request $request,$id){
        $this->validateId($id);
        $request->validate(
            ['password'=>'required|confirmed|string|min:8']
        );
//        dd($request->all());
        $this->user->password = Hash::make($request->passowrd);
        $status = $this->user->save();
        if($status){
            $request->session()->flash('success','user password updated successfully.');
        }else{
            $request->session()->flash('error','Sorry!, error while updating user password');
        }
        return redirect()->back();
    }

}

resources/views/admin/user/form.blade.php
@extends('layouts.dashboard')
@section('title','User Form')
@section('content-header')
<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1>User Manager</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">User Form</li>
            </ol>
        </div>
    </div>
</div><!-- /.container-fluid -->
@endsection
@section('content')
    <div class="row">
        <!-- /.col -->
        <div class="col-md-12">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h1 class="card-title">User Form</h1>
                    <a href="{{ route('user.index') }}" title="List All User" class="btn btn-info btn-sm btn-circle float-right"><i class="fa fa-eye"></i></a>
                </div>
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all()  as $key => $error)
                                @if($key == 0)
                                <li>{{ $error }}</li>
                                {!! readLoud($error) !!}
                                @endif
                            @endforeach
                        </ul>
                    </div>
                @endif
                <!-- /.card-header -->
                <div class="card-body">
                @if(isset($user_detail))
                        {{ Form::open(['url'=>route('user.update',$user_detail->id) ,'class'=>'form','files'=>true]) }}
                        @method('patch')
                    @else
                        {{ Form::open(['url'=>route('user.store') ,'class'=>'form','files'=>true]) }}
                    @endif
                        <div class="form-group row">
                            {{ Form::label('name','Name',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::text('name',@$user_detail->name,['class'=>'form-control form-control-sm','id'=>'name','required'=>true,'placeholder'=>'Enter your name']) }}
                                @error('name')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        @if(!isset($user_detail))
                        <div class="form-group row">
                            {{ Form::label('email','Email Address',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::text('email',@$user_detail->email,['class'=>'form-control form-control-sm','id'=>'email','required'=>true,'placeholder'=>'Enter user email address']) }}
                                @error('email')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('password','Password',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::password('password',['class'=>'form-control form-control-sm','id'=>'password','required'=>true,'placeholder'=>'Enter  password']) }}
                                @error('password')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('confirmation_password','Re-password',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::password('password_confirmation',['class'=>'form-control form-control-sm','id'=>'confirmation_password','required'=>true,'placeholder'=>'Re-enter  password ']) }}
                                @error('confirmation_password')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        @endif
                    <div class="form-group row">
                        {{ Form::label('address','DOB',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                        <div class="col-sm-12 col-md-7">
                            {{ Form::date('dob',@$user_detail->userInfo->dob,['class'=>'form-control form-control-sm','id'=>'dob','required'=>false,'placeholder'=>'Enter your dob']) }}
                            @error('dob')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>
                        <div class="form-group row">
                            {{ Form::label('role','User',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::select('role',['user'=>"User"],@$user_detail->role,['class'=>'form-control form-control-sm','id'=>'role','required'=>true]) }}
                                @error('role')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('gender','Gender',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::select('gender',['male'=>"Male",'female'=>"Female",'other' => "Other"],@$user_detail->gender,['class'=>'form-control form-control-sm','id'=>'gender','required'=>true]) }}
                                @error('gender')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ Form::label('status','Status',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                            <div class="col-sm-12 col-md-7">
                                {{ Form::select('status',['active'=>"Active",'inactive'=>"Inactive"],@$user_detail->status,['class'=>'form-control form-control-sm','id'=>'status','required'=>true]) }}
                                @error('status')
                                <span class="alert alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                    <div class="form-group row">
                        {{ Form::label('image_update','PP',['class'=>'col-sm-12 col-md-5 text-md-right']) }}
                        <div class="col-sm-12 col-md-4">
                            {{ Form::file('photo',['id'=>'image_update','required'=>(isset($user_detail) ? false : true),'accept'=>"image/*",'onchange'=>"readURL(this,'thumb')"]) }}
                            @error('photo')
                            <span class="alert alert-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="col-md-3">
                            @if(isset($user_detail) && !empty($user_detail->userInfo->photo))
                                <img src="{{ asset("uploads/user/".$user_detail->userInfo->photo) }}" alt="" id="thumb" class="img-fluid img-thumbnail">
                            @else
                                <img src="" alt="" id="thumb" class="img-fluid img-thumbnail">
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12 col-md-7 offset-md-5">
                            <button type="submit" class="btn btn-success btn-block btn-sm" >Submit</button>
                        </div>
                    </div>
                    {{ Form::close() }}
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
@endsection

@section('scripts')
<script>
readURL= function(input,image_id){
    if(input.files && input.files[0]){
        var reader  = new FileReader();
        reader.onload = function (e){
            $('#'+image_id)
                .attr('src',e.target.result);
        };
        reader.readAsDataURL(input.files[0]);
    }
}
</script>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.dashboard')
@section('title',isset($user) ? $user : 'User List')
@section('content-header')
<div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1>User Manager</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">{{ isset($user) ? $user : 'User List' }}</li>
            </ol>
        </div>
    </div>
</div><!-- /.container-fluid -->
@endsection
@section('content')
    <div class="row">
        <!-- /.col -->
        <div class="col-md-12">
        <div class="card card-primary card-outline">
                <div class="card-header">
                    <h1 class="card-title">{{ isset($user) ? $user : 'All User List' }}</h1>
                    @if(isset($user))
                    <a href="{{ route('user.index') }}" title="Add User" class=" float-right btn btn-success btn-circle"><i class="fa fa-eye"></i></a>
                    @else
                    <a href="{{ route('user.create') }}" title="Add User" class=" float-right btn btn-success btn-circle"><i class="fa fa-plus"></i></a>
                    @endif
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="container-fluid">

                        <table class="table table-striped table-hover data-table">
                            <thead class="thead-dark">
                            <th>Name</th>
                            <th>Email</th>
                            <th>Gender</th>
                            @if(isset($is_all))
                            <th>Role</th>
                            @endif
                                <th>Image</th>
                                <th>Status</th>
                                <th>Action</th>
                            </thead>
                            <tbody>
                            @if($all_users->count())
                                @foreach($all_users as $data)
                                <tr>
                                    <td>{{$data->name}}</td>
                                    <td>{{$data->email}}</td>
                                    <td>{{ @$data->userInfo->gender }}</td>
                            @if(isset($is_all))
                                    <td>
                                        {{ $data->role }}
                                    </td>
                                @endif
                                    <td>
                                    @if($data->userInfo)
                                        <a href="{{ asset('uploads/user/'.$data->userInfo->photo) }}" data-lightbox = "image-{{ $data->id }}" data-title = {{ $data->title }}>
                                            <div class="thumb"><img src="{{ asset('uploads/user/'.$data->userInfo->photo) }}" width = "40" height = "40" ></div>
                                        </a>
                                    @endif
                                    </td>
                                    <td>
                                        <a href="{{ route('user-change-status',[$data->id,$data->status]) }}" class="badge badge-{{ $data->status == 'active' ? 'success' : 'danger' }}">{{ $data->status == 'active' ? 'Active' : 'Inactive' }}</a>
                                    </td>
                                    <td>
                                        <a href="{{ route('change-pwd',$data->id) }}" title="Update Password" class="btn btn-secondary btn-sm btn-circle">
                                            <i class="fa fa-key"></i>
                                        </a>
                                        <a href="{{ route('user.edit',$data->id) }}" title="Edit this user" class="btn btn-primary btn-sm btn-circle">
                                            <i class="fa fa-pen"></i>
                                        </a>
                                        <a href="javascript:;" title="Delete this user" class="btn btn-warning btn-sm btn-circle delete-btn">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                        {{ Form::open(['url' => route('user.destroy',$data->id) , 'class' => 'delete-form' ]) }}
                                            @method('delete')
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
@endsection
@section('scripts')
<script type="text/javascript">
$(document).ready( function () {
    $('.data-table').DataTable();
} ); 
</script>
@endsection